spring:
   datasource:
      username: inventory_tracker
      password: inventory_tracker
      url: jdbc:mysql://localhost:3306/inventory_tracker
      
   jpa:
     hibernate:
       ddl-auto: none   
     show-sql: true
      
   sql:
     init:
       mode: never
       
       
          